sudo: false
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - 3.7-dev
install:
  - pip install codecov "pytest>=4.3" pytest-cov
script:
  - pytest --cov=terminal_palette
after_success:
  - codecov
